SHELL=/bin/bash

APP_VERSION  ?= 0.0.0
STORAGE_PORT ?= 5432

CONTAINER_REGISTRY ?= us-east1-docker.pkg.dev/tradeforge-e761b/backend
IMAGE_TAG          ?= latest

MIGRATIONS_DIR ?= ./database/sql/migrations
